### PR TITLE
ECR1271 

### LINKED ISSUE #9: Demo for ERC1271 - Standard Signature Validation Method
ERC 1271 - Externally Owned Accounts (EOA) can sign messages with their associated private keys, but currently contracts cannot. It propose a standard way for any contracts to verify whether a signature on a behalf of a given contract is valid. This is possible via the implementation of a isValidSignature(hash, signature) function on the signing contract, which can be called to validate a signature.

Resources to follow: 
1. https://eips.ethereum.org/EIPS/eip-1271
2. https://docs.cow.fi/tutorials/how-to-place-erc-1271-smart-contract-orders/the-basics-of-erc-1271
3. https://www.youtube.com/watch?v=sc1x_du6UXk&ab_channel=EthereumCatHerders

### PR DESCRIPTION
**Pull request by Hares27**

### CODE REVIEW

**Comment by bansaltushar014** [comment]
Hi @Hares27 ,

Could you please add a little description or one liner about ERC 1271 in the below comment? 

Also please let me know if you are done with the commits.

**Comment by Hares27** [comment]
Hello @bansaltushar014 , I added  the description about the standard. Please let me know if anything you want to add.

**Comment by bansaltushar014** [comment]
Sure @Hares27 , I will review it.

**Comment by bansaltushar014** [comment]
Please rename the folder name from VerifySignature to ERC1271

**Comment by Hares27** [comment]
Hello @bansaltushar014 , I have renamed the "VerifySignature.sol".

**Comment by bansaltushar014** [comment]
Reviewed. Merged.

**Pull request merged**
